server:
  port: 48080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/petverse
    username: root
    password: P@ssw0rd
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

jwt:
  secret: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXk=  # Base64 encoded key
  access-expiration-in-ms: 60000  # 1 Minute
  refresh-expiration-in-ms: 3600000  # 1 Hours

logging:
  level:
    org.hibernate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
    #com.zaxxer.hikari: DEBUG

